ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ZOHO_CONNECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ZOHO_DISCONNECTED';

ALTER TABLE "DealHandoff" ALTER COLUMN "clientCrmProvider" SET DEFAULT 'ZOHO';
ALTER TABLE "ClientCrmRecord" ALTER COLUMN "provider" SET DEFAULT 'ZOHO';
