"use client";

import { useEffect, useRef, useState } from "react";
import { FilePenLine, FileText, Plus, Save, Sparkles, UserRound } from "lucide-react";
import { MultiCrmCard, MultiCrmInnerPanel, MultiCrmTag } from "@/components/ui/MultiCrmCard";
import { useClientAccount } from "@/context/ClientAccountContext";
import { readApiJson } from "@/lib/http/client-api";

type Channel = "CALL" | "SMS" | "EMAIL";
interface Contact { id: string; firstName: string; lastName: string; company: string | null; }
interface Analysis { id: string; leadScore: number; temperature: string; contact: { firstName: string; lastName: string } | null; }
interface Template { key: string; name: string; channel: Channel; purpose: string; }
interface Script { id: string; title: string; purpose: string; content: string; channel: Channel; source: "GENERATED" | "MANUAL" | "TEMPLATE"; isManualOverride: boolean; contact: { firstName: string; lastName: string; company: string | null } | null; }

export default function ScriptsPage() {
  const { activeClientAccount, isClientAccountReady } = useClientAccount();
  const [contacts, setContacts] = useState<Contact[]>([]); const [analyses, setAnalyses] = useState<Analysis[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const [scripts, setScripts] = useState<Script[]>([]);
  const [contactId, setContactId] = useState(""); const [leadAnalysisId, setLeadAnalysisId] = useState(""); const [templateKey, setTemplateKey] = useState("FOLLOW_UP"); const [channel, setChannel] = useState<Channel>("EMAIL"); const [purpose, setPurpose] = useState("Follow up after a discovery conversation");
  const [selected, setSelected] = useState<Script | null>(null); const [draft, setDraft] = useState({ title: "", purpose: "", content: "", channel: "EMAIL" as Channel });
  const [isLoading, setIsLoading] = useState(false); const [isWorking, setIsWorking] = useState(false); const [message, setMessage] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  const clientRequestVersion = useRef(0);
  const currentClientAccountId = useRef(activeClientAccount.id);
  currentClientAccountId.current = activeClientAccount.id;

  useEffect(() => {
    if (!isClientAccountReady) return;
    const controller = new AbortController();
    const requestVersion = ++clientRequestVersion.current;
    const clientAccountId = activeClientAccount.id;

    setIsLoading(true); setMessage(null); setContacts([]); setAnalyses([]); setTemplates([]); setScripts([]); setSelected(null); setContactId(""); setLeadAnalysisId(""); setDraft({ title: "", purpose: "", content: "", channel: "EMAIL" });

    const load = async () => {
      try {
        const [contactsResponse, analysesResponse, scriptsResponse, templatesResponse] = await Promise.all([
          fetch("/api/contacts", { cache: "no-store", signal: controller.signal }),
          fetch("/api/lead-analyses", { cache: "no-store", signal: controller.signal }),
          fetch("/api/scripts", { cache: "no-store", signal: controller.signal }),
          fetch("/api/scripts/templates", { cache: "no-store", signal: controller.signal }),
        ]);
        const [contactsPayload, analysesPayload, scriptsPayload, templatesPayload] = await Promise.all([
          readApiJson<{ success: true; contacts: Contact[] }>(contactsResponse),
          readApiJson<{ success: true; analyses: Analysis[] }>(analysesResponse),
          readApiJson<{ success: true; scripts: Script[] }>(scriptsResponse),
          readApiJson<{ success: true; templates: Template[] }>(templatesResponse),
        ]);
        if (controller.signal.aborted || requestVersion !== clientRequestVersion.current || currentClientAccountId.current !== clientAccountId) return;
        setContacts(contactsPayload.contacts); setAnalyses(analysesPayload.analyses); setScripts(scriptsPayload.scripts); setTemplates(templatesPayload.templates);
      }
      catch (error) { if (controller.signal.aborted || requestVersion !== clientRequestVersion.current || currentClientAccountId.current !== clientAccountId) return; setMessage({ tone: "error", text: error instanceof Error ? error.message : "Script workspace data could not be loaded." }); } finally { if (!controller.signal.aborted && requestVersion === clientRequestVersion.current && currentClientAccountId.current === clientAccountId) setIsLoading(false); }
    };

    void load();
    return () => controller.abort();
  }, [activeClientAccount.id, isClientAccountReady]);
  const useTemplate = (key: string) => { const template = templates.find((item) => item.key === key); setTemplateKey(key); if (template) { setChannel(template.channel); setPurpose(template.purpose); } };
  const chooseScript = (script: Script) => { setSelected(script); setDraft({ title: script.title, purpose: script.purpose, content: script.content, channel: script.channel }); };
  const generate = async () => { const requestVersion = clientRequestVersion.current; const clientAccountId = activeClientAccount.id; setIsWorking(true); setMessage(null); try { const response = await fetch("/api/scripts/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contactId: contactId || undefined, leadAnalysisId: leadAnalysisId || undefined, templateKey, channel, purpose }) }); const data = await readApiJson<{ success: true; script: Script }>(response); if (requestVersion !== clientRequestVersion.current || currentClientAccountId.current !== clientAccountId) return; const script = data.script; setScripts((current) => [script, ...current]); chooseScript(script); setMessage({ tone: "success", text: "Generated script saved. Review and edit it before use." }); } catch (error) { if (requestVersion !== clientRequestVersion.current || currentClientAccountId.current !== clientAccountId) return; setMessage({ tone: "error", text: error instanceof Error ? error.message : "The script could not be generated." }); } finally { if (requestVersion === clientRequestVersion.current && currentClientAccountId.current === clientAccountId) setIsWorking(false); } };
  const save = async (manual = false) => { if (!draft.title.trim() || !draft.purpose.trim() || !draft.content.trim()) { setMessage({ tone: "error", text: "Enter a title, purpose, and content before saving." }); return; } const requestVersion = clientRequestVersion.current; const clientAccountId = activeClientAccount.id; setIsWorking(true); setMessage(null); try { const endpoint = selected && !manual ? `/api/scripts/${selected.id}` : "/api/scripts"; const method = selected && !manual ? "PATCH" : "POST"; const response = await fetch(endpoint, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...draft, contactId: contactId || undefined, leadAnalysisId: leadAnalysisId || undefined }) }); const data = await readApiJson<{ success: true; script: Script }>(response); if (requestVersion !== clientRequestVersion.current || currentClientAccountId.current !== clientAccountId) return; const script = data.script; setScripts((current) => current.some((item) => item.id === script.id) ? current.map((item) => item.id === script.id ? script : item) : [script, ...current]); chooseScript(script); setMessage({ tone: "success", text: manual ? "Manual script saved." : "Script correction saved and audited." }); } catch (error) { if (requestVersion !== clientRequestVersion.current || currentClientAccountId.current !== clientAccountId) return; setMessage({ tone: "error", text: error instanceof Error ? error.message : "The script could not be saved." }); } finally { if (requestVersion === clientRequestVersion.current && currentClientAccountId.current === clientAccountId) setIsWorking(false); } };

  return <div className="space-y-6 text-crm-text font-sans">
    <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="flex items-center gap-2"><FilePenLine className="w-5 h-5 text-secondary-pink" /><h1 className="text-2xl font-bold tracking-tight">Sales Script Architect</h1></div><p className="text-xs text-crm-text-muted font-mono mt-1">Context-aware, editable sales communication for the active client account.</p></div><MultiCrmTag variant="magenta">{activeClientAccount.name}</MultiCrmTag></div>
    <div className="grid grid-cols-1 xl:grid-cols-5 gap-6"><MultiCrmCard className="xl:col-span-2 space-y-4"><div className="flex items-center gap-2 border-b border-crm-border-strong pb-3"><Sparkles className="w-4 h-4 text-secondary-pink" /><h2 className="text-sm font-semibold">Generate with context</h2></div>
      <div className="space-y-1.5 font-mono text-xs"><label className="text-[10px] text-crm-text-muted">Reusable template</label><select value={templateKey} onChange={(event) => useTemplate(event.target.value)} className="w-full bg-crm-inner border border-crm-border-strong rounded-xl p-2 text-crm-text"><option value="">Custom generation</option>{templates.map((template) => <option key={template.key} value={template.key}>{template.name}</option>)}</select></div>
      <div className="space-y-1.5 font-mono text-xs"><label className="text-[10px] text-crm-text-muted">Channel</label><select value={channel} onChange={(event) => setChannel(event.target.value as Channel)} className="w-full bg-crm-inner border border-crm-border-strong rounded-xl p-2 text-crm-text"><option value="CALL">Call script</option><option value="SMS">SMS follow-up</option><option value="EMAIL">Email follow-up</option></select></div>
      <div className="space-y-1.5 font-mono text-xs"><label className="text-[10px] text-crm-text-muted">Contact context</label><select value={contactId} onChange={(event) => setContactId(event.target.value)} className="w-full bg-crm-inner border border-crm-border-strong rounded-xl p-2 text-crm-text"><option value="">Account-level script</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.firstName} {contact.lastName}{contact.company ? ` · ${contact.company}` : ""}</option>)}</select></div>
      <div className="space-y-1.5 font-mono text-xs"><label className="text-[10px] text-crm-text-muted">Lead-analysis context</label><select value={leadAnalysisId} onChange={(event) => setLeadAnalysisId(event.target.value)} className="w-full bg-crm-inner border border-crm-border-strong rounded-xl p-2 text-crm-text"><option value="">No analysis selected</option>{analyses.map((analysis) => <option key={analysis.id} value={analysis.id}>{analysis.contact ? `${analysis.contact.firstName} ${analysis.contact.lastName}` : "Account"} · {analysis.temperature} · {analysis.leadScore}/100</option>)}</select></div>
      <div className="space-y-1.5 font-mono text-xs"><label className="text-[10px] text-crm-text-muted">Purpose</label><input value={purpose} onChange={(event) => setPurpose(event.target.value)} className="w-full bg-crm-inner border border-crm-border-strong rounded-xl p-2 text-crm-text" /></div><button onClick={() => void generate()} disabled={isWorking} className="w-full py-3 rounded-xl bg-secondary-pink/20 border border-secondary-pink/40 text-secondary-pink font-bold text-xs hover:bg-secondary-pink/30 disabled:opacity-50 cursor-pointer">{isWorking ? "Generating…" : "Generate and save script"}</button><p className="text-[10px] font-mono text-crm-text-muted">Brand, contact, latest interactions, and optional lead analysis are retrieved server-side.</p></MultiCrmCard>
      <MultiCrmCard className="xl:col-span-3 space-y-4"><div className="flex items-center justify-between border-b border-crm-border-strong pb-3"><div className="flex items-center gap-2"><FileText className="w-4 h-4 text-primary-cyan" /><h2 className="text-sm font-semibold">Full manual editor</h2></div>{selected && <MultiCrmTag variant={selected.isManualOverride ? "magenta" : "cyan"}>{selected.isManualOverride ? "EDITED" : selected.source}</MultiCrmTag>}</div><div className="grid grid-cols-1 md:grid-cols-2 gap-3 font-mono text-xs"><div><label className="text-[10px] text-crm-text-muted">Title</label><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="e.g. Discovery follow-up" className="mt-1 w-full bg-crm-inner border border-crm-border-strong rounded-xl p-2 text-crm-text" /></div><div><label className="text-[10px] text-crm-text-muted">Purpose</label><input value={draft.purpose} onChange={(event) => setDraft({ ...draft, purpose: event.target.value })} placeholder="What should this achieve?" className="mt-1 w-full bg-crm-inner border border-crm-border-strong rounded-xl p-2 text-crm-text" /></div></div><div className="space-y-1 font-mono text-xs"><label className="text-[10px] text-crm-text-muted">Script content</label><textarea rows={15} value={draft.content} onChange={(event) => setDraft({ ...draft, content: event.target.value })} placeholder="Write a script manually or generate one from the context panel…" className="w-full bg-crm-inner border border-crm-border-strong rounded-xl p-3 text-xs leading-relaxed text-crm-text" /></div><div className="flex flex-wrap justify-end gap-3 pt-3 border-t border-crm-border-strong"><button onClick={() => { setSelected(null); setDraft({ title: "", purpose: "", content: "", channel }); }} className="px-4 py-2 rounded-xl bg-crm-inner border border-crm-border-strong text-xs text-crm-text-muted cursor-pointer"><Plus className="inline w-3.5 h-3.5 mr-1" />New manual</button><button onClick={() => void save(!selected)} disabled={isWorking} className="px-4 py-2 rounded-xl bg-primary-cyan text-slate-950 text-xs font-bold disabled:opacity-50 cursor-pointer"><Save className="inline w-3.5 h-3.5 mr-1" />{isWorking ? "Saving…" : "Save script"}</button></div></MultiCrmCard></div>
    {message && <p role="status" className={`rounded-xl border px-4 py-3 text-xs font-mono ${message.tone === "success" ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-400" : "border-rose-500/30 bg-rose-500/10 text-rose-300"}`}>{message.text}</p>}
    <MultiCrmCard className="space-y-4"><div className="flex items-center justify-between border-b border-crm-border-strong pb-3"><div className="flex items-center gap-2"><UserRound className="w-4 h-4 text-primary-cyan" /><h2 className="text-sm font-semibold">Saved scripts</h2></div><span className="text-[10px] font-mono text-crm-text-muted">{isLoading ? "Loading…" : `${scripts.length} records`}</span></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{scripts.map((script) => <button key={script.id} onClick={() => chooseScript(script)} className={`text-left p-4 rounded-xl border transition-colors cursor-pointer ${selected?.id === script.id ? "border-primary-cyan/50 bg-primary-cyan/10" : "border-crm-border-strong bg-crm-inner hover:border-primary-cyan/30"}`}><div className="flex justify-between gap-2"><span className="text-xs font-bold truncate">{script.title}</span><span className="text-[10px] font-mono text-primary-cyan">{script.channel}</span></div><p className="mt-2 text-[11px] text-crm-text-muted line-clamp-2">{script.content}</p><p className="mt-2 text-[10px] font-mono text-slate-500">{script.contact ? `${script.contact.firstName} ${script.contact.lastName}` : "Account"} · {script.isManualOverride ? "Edited" : script.source}</p></button>)}</div>{!isLoading && !scripts.length && <p className="py-5 text-center text-xs text-crm-text-muted">No scripts have been saved for this client account.</p>}</MultiCrmCard>
  </div>;
}
